version: '3'

services:
  app:
    build:
      context: ./dockerfiles/php
    volumes:
      - .:/code
    depends_on:
      - database
    ports:
      - "9000:9000"

  nginx:
    build:
      context: ./dockerfiles/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"

  database:
    build:
      context: ./dockerfiles/database
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
